# yaml-language-server: $schema=https://github.com/bherbruck/bromq/releases/latest/download/bromq-config.schema.json

users:
  - username: admin
    password: admin
  - username: bridge
    password: bridge

acl_rules:
  - username: admin
    topic: "#"
    permission: pubsub
  - username: bridge
    topic: "$$bridge/#"
    permission: pubsub
